packages/biscuit/structures/builders/slash/ApplicationCommand.ts
packages/biscuit/structures/builders/slash/ApplicationCommandOption.ts

fix: types

---

packages/biscuit/Routes.ts
packages/biscuit/Session.ts
packages/biscuit/structures/builders/slash/ApplicationCommand.ts
packages/biscuit/structures/builders/slash/ApplicationCommandOption.ts

feat(biscuit): Session.editProfile()

---

packages/biscuit/Routes.ts
packages/biscuit/structures/guilds.ts

feat(Guild): edit > Splash, Banner, SplashDiscovery, leave()

---

packages/api-types/discord.ts
packages/api-types/shared.ts
packages/biscuit/structures/Message.ts
packages/biscuit/structures/ThreadMember.ts
packages/biscuit/structures/channels.ts
packages/biscuit/structures/guilds.ts

Docs: Channels

---

packages/biscuit/structures/Message.ts
packages/biscuit/structures/channels.ts

The property was added to the corresponding channels and the way of use was modified.

fix(channels): permissionOverwrites

---

README.md
packages/api-types/src/index.ts
packages/core/src/index.ts

fix: readme example

---

packages/core/src/structures/user.ts

n128 is stupid

---

packages/api-types/src/utils/routes.ts
packages/core/src/structures/emojis.ts

- Fetch user that created emoji
- Setter emoji's name

feat(Emoji): Add Methods

---

packages/core/src/structures/channels.ts

this changes mixins to a namespace

refactor: channels.ts

---

packages/core/src/errors/BiscuitError.ts
packages/core/src/errors/ErrorCodes.ts
packages/core/src/errors/ErrorMessages.ts
packages/core/src/errors/index.ts

The error codes and most of the error messages were taken/inspired from the Discord.js library

 Implementation of error system (surely)

---

src/client/base.ts
src/client/onmessagecreate.ts
src/index.ts

with marcrock whatsapp support

fix custom context in prefix commands

---

src/client/onmessagecreate.ts

I only added the damn .slice, I didn't touch the rest....

ig, fix subcommand groups

---

src/builders/SelectMenu.ts

fix: mentionables defaults

---

src/components/componentcontext.ts

Using getter the methods are not executed properly, generating errors. 
"Marcrock was right"

fix: errors in componentcontext class and add docs

---

src/commands/applications/menucontext.ts

fix: modal method

---

src/structures/Interaction.ts

this should fix the issue with modal responses that had to be run twice to be responded

fix: modal response. ft. marcrock in whatsapp

---

package.json
pnpm-lock.yaml
src/api/Routes/channels.ts
src/builders/Poll.ts
src/builders/index.ts
src/common/shorters/messages.ts
src/common/types/write.ts
src/events/hooks/message.ts
src/structures/Message.ts
src/structures/Poll.ts
src/structures/index.ts
src/websocket/SharedTypes.ts

feat: add polls

---

biome.json
package.json
pnpm-lock.yaml
src/api/api.ts
src/cache/resources/default/guild-related.ts
src/cache/resources/overwrites.ts
src/client/base.ts
src/client/client.ts
src/client/collectors.ts
src/client/httpclient.ts
src/client/onmessagecreate.ts
src/client/workerclient.ts
src/commands/applications/chat.ts
src/commands/applications/shared.ts
src/commands/decorators.ts
src/commands/handler.ts
src/commands/optionresolver.ts
src/common/it/logger.ts
src/common/it/utils.ts
src/common/types/util.ts
src/components/handler.ts
src/events/hooks/integration.ts
src/events/hooks/typing.ts
src/index.ts
src/langs/router.ts
src/structures/Interaction.ts
src/structures/Message.ts
src/structures/channels.ts
src/structures/extra/functions.ts
src/websocket/discord/shard.ts

Update stuff:
- Biome and fixes
- discord-api-types
- ws
- @commitlint/cli
- @types/node
- lint-staged

chore: updates

---

src/events/handler.ts

refactor: remove deprecations

---

src/structures/Message.ts

Prior to this pr the embeds went through the `toCamelCase` changing its type and making it difficult to use.

fix: embeds in messages

---

src/components/handler.ts

fix: default props in components

---

src/structures/Interaction.ts
src/structures/channels.ts

Discord changed how attachments are handled when you edit a message making [this commit](https://github.com/tiramisulabs/seyfert/commit/006a9f390fa5685c88fcd77b82d95c4308ccdd48) error prone

fix: embeds with attachments

---

src/deps/mixer.ts

fix: Protoype

---

src/commands/handler.ts
src/components/handler.ts
src/events/handler.ts
src/langs/handler.ts

Especially for running in the edge (cof cof cloudflare workers)

A way to set values in handlers 

---

src/types/payloads/application.ts

Discord added approximate_user_install_count parameter to Application

feat(APIApplication): approximate user install count

---

package.json
pnpm-lock.yaml
src/cache/adapters/default.ts
src/cache/adapters/limited.ts
src/cache/adapters/types.ts
src/cache/adapters/workeradapter.ts
src/cache/index.ts
src/client/base.ts
src/client/client.ts
src/client/workerclient.ts
src/events/handler.ts

1. use an object instead of an array to disable cache
2. option to disable cache on events
3. implement start method on cache adapters

feat: cache update

---

src/cache/index.ts

fix: cache truco

---

src/cache/index.ts

Gato didn't tell me that shit.

fix: cache truco 2

---

src/commands/optionresolver.ts

cactus truco

---

src/commands/applications/chatcontext.ts

feat(context): auto remove thinking when use message commands

---

src/common/it/formatter.ts
src/common/shorters/messages.ts
src/structures/channels.ts

Sorry for the commit spam, i didn't rebase it correctly.

feat(MessageMethods#list): implements /channels/{channel.id}/messages for getting bulk messages

---

src/deps/mixer.ts

@MARCROCK22 @socram03 can we check if this breaks anything else

fix(Mixin): priorize second class keys

---

src/client/base.ts

Since marcrock is lazy, I came and decided to remove this which is literally not used anywhere.

fix: removed really necessary locations

---

src/commands/applications/chatcontext.ts
src/commands/applications/entrycontext.ts
src/components/componentcontext.ts
src/components/modalcontext.ts

Esto lo hago, por los momos, por los momos, por los momos.

fix: esto lo hago

---

src/common/shorters/guilds.ts
src/structures/channels.ts

Free did this a couple of weeks ago... So, I think seyfert should have it too.

feat: return channel type in channel guild create

---

src/components/componentcommand.ts

this change allows using regex as customId

feat: use regex in customId component command

---

biome.json
src/api/Router.ts
src/api/Routes/cdn.ts
src/api/Routes/channels.ts
src/api/Routes/guilds.ts
src/api/utils/constants.ts
src/common/shorters/channels.ts
src/common/shorters/guilds.ts
src/structures/channels.ts
src/types/payloads/permissions.ts
src/types/payloads/user.ts
src/types/rest/channel.ts
src/types/rest/guild.ts

Apply recent Discord API changes 
