package.json, packages/api-types/package.json, packages/cache/package.json, packages/core/package.json, packages/extra/package.json, packages/extra/src/collectors.ts, packages/extra/src/index.ts, packages/extra/tsconfig.json, packages/extra/tsup.config.ts, packages/ws/package.json, turbo.json
Hey! You're doing a great job with the lib and I wanted to contribute so I made an 'extra' package which currently only has collectors and they can be used in any event.
Cool example
```ts
import { GatewayIntents } from '@biscuitland/api-types';
import { Session, Events } from '@biscuitland/core';
import { Collector } from '@biscuitland/extra';
const session = new Session({
token: 'token',
intents: GatewayIntents.MessageContent | GatewayIntents.GuildMessages | GatewayIntents.GuildMembers
});
session.events.on('messageCreate', async (message) => {
if (message.content === '!nick') {
let nick = message.member?.nickname ?? message.author.username;
const m = await message.reply({
content: `your nickname is ${nick}`
});
const collector = new Collector(session, {
event: 'guildMemberUpdate', …
```
=> feat(extra): collectors

packages/core/src/structures/members.ts, packages/core/src/structures/special/permissions.ts, packages/core/src/structures/user.ts
`USER_DEFAULT_AVATAR` of `api-types` returns the default avatar with `.png` as extension (as it should be) but `avatarURL` adds the format and size specified in `options` parameter.
The `USER_DEFAULT_AVATAR` endpoint has no formats other than `.png` and the size doesn't matter, it will always be 256x256.
The `Member#avatarURL` shouldn't return the default avatar if they don't have one within the guild. It should look for the user's avatar or return `undefined`/`null` instead. I made it return the user's avatar but if this is not how you expect it to work, you can change it.
Thanks :)!
=> fix: avatarURL doesn't correctly return the default avatar

packages/api-types/src/utils/routes.ts
Discord returns 404 when trying to GET /users/@me/guilds/
=> fix(routes): remove trailing slash from USER_GUILDS

package-lock.json, src/builders/SelectMenu.ts
Replaced `setDefaults` method from MentionableSelectMenu into `setDefaultMentionables` as pair as the other select menu times.
=> refactor: change method name for MentionableSelectMenu builder

src/components/index.ts
This commit adds the export statement export * from './componentcontext'; to the index.ts file.
=> feat: add componentcontext export to index

src/api/Router.ts, src/common/shorters/emojis.ts, src/structures/GuildMember.ts, src/structures/User.ts
1. Removed dynamicAvatarURL from GuildMember, as we could have the same output from GuildMember#user
2. Added a default extension option in avatarURL method, to return a gif if the user has a gif avatar and if not return specified extension.
These approaches are similar to discord.js, but i feel these are useful as this makes the user write less code on their end.
=> feat: new changes to avatarURL method over GuildMember & User

src/client/client.ts, src/common/it/colors.ts
This PR introduces a fix to the argument and options parser, the recent build for seyfert was replacing the parsers provided by the user with it's own default parser removing the flexibility.
Below are the steps to reproducing this issue.
1. Construct a client
2.  Pass in your own argument parser
3. Parser doesn't work, due to being overridden
Basically the passed in options for the arguments parser or options parser are not working for example, i tried using the YunaParser and it failed, due to being overridden by the library's default parser settings.
=> Parsers overridden during client initialization making external parsers from not working.

biome.json, src/api/Routes/guilds.ts, src/cache/index.ts, src/cache/resources/bans.ts, src/client/base.ts, src/client/client.ts, src/common/index.ts, src/common/it/formatter.ts, src/common/shorters/bans.ts, src/index.ts, src/structures/Guild.ts, src/structures/GuildBan.ts, src/structures/channels.ts
This PR introduces a new structure the `GuildBan` and it's resources, cache and more, Also introduces a new Util class the `Formatter` and some certain changes to types and voice channel methods.
- GuildBans ✅
- Voice Channel Methods ✅
- Formatter ✅
The PR solves a lot of issues future devs might have faced or something i personally feel, is that there was a need of the GuildBan structural change in the library to support fetching/listing of bans and ofcourse a cache to be maintained.
The formatter is a personal preference as it makes code cleaner and efficient instead of memorizing all discord markdowns and using them with text. Lastly `members` method has been added to voice channels to return the members in the voice channel.
=> feat: guild bans, formatter and minor functionality changes.

src/common/it/formatter.ts, src/events/hooks/guild.ts, src/structures/GuildBan.ts, src/structures/GuildEmoji.ts, src/structures/GuildMember.ts, src/structures/GuildRole.ts, src/structures/User.ts, src/structures/channels.ts
- Added `toString` to `GuildRole` & `RoleShorter`.
- Added multiple mention formatters (role, channel, user).
- Added emoji formatter.
Overall changed the way of `toString` method in most of the shorters and structures, instead of returning base strings i am now returing the output the formatters.
=> chore: improve toString output with newly added formatters

src/client/base.ts, src/websocket/discord/sharder.ts
Adds support to .mjs, .ts and .js extensions when loading the seyfert.config file.
=> feat: support .cjs, .mjs, .ts, .mts and .cts extensions in seyfert.config file

src/types/rest/channel.ts
Fixed a problem where the `Permissions` type returned `any` due to an incorrect import.
=> fix: 'Permissions' type truco

src/commands/handle.ts
This PR should improve code logic by avoiding an additional permissions calculation when app has `Administrator`
=> chore: early conditional

src/structures/Interaction.ts
This Pull Requests fix problem not deleting key in modal map when `.run` is not provided.
=> Fix modal execution

src/commands/decorators.ts, src/commands/handle.ts, src/commands/handler.ts, src/structures/extra/BitField.ts, src/structures/extra/Permissions.ts
For some reason, discord takes the permissions of the parent command to manage the permissions of the sub-commands or command groups, forcing a server side check of the user permissions that discord already calculates.
=> Overwritting permissions for child commands

src/builders/Embed.ts
Both the Footer & Author components of EmbedBuilder imply that the syntax for setting the icon is:
```
.setAuthor({ name: 'John Doe', iconURL: '...' })
```
However, it appears that this should be `iconUrl`
=> Examples of Footer & Author in EmbedBuilder don't match

src/events/handler.ts
A couple of days ago I noticed a strange behavior in the voiceStateUpdate event.
What was happening was this:
https://github.com/user-attachments/assets/12d422db-9611-4fb2-81b4-e8b84fda849a
And this is what is supposed to happen:
https://github.com/user-attachments/assets/91bd95d7-68bd-4ad3-8b3e-fdc9da7c1d0b
=> fix: update cache before executing the event?

src/structures/Message.ts
Are we being serious?? 😭 
WE HAVE TYPES FOR A REASON PLEASE
`messageReference` incase of Menu Command
`@me` when ran in dms
=> fix(structures/message/get url): NON NULL ASSERTION? BFFR

src/builders/SelectMenu.ts
(This is the real one.)
I think the generic `Interaction` is useless since is not used in any place.
=> fix: removed another 'ts-expect-error'...?

src/langs/router.ts
When using the `ctx.t` proxy without any path (i.e., `ctx.t.get()`), as shown in the [documentation](https://www.seyfert.dev/guide/i18n/languages#using-translations-in-your-commands), it causes unexpected errors when the user's locale hasn't been configured in Seyfert.
This is because, when the route is empty (`[]`), the function returns `value` immediately after fetching it from `langs[locale]`. If the locale does not exist in `langs`, `value` becomes `undefined`—but since there’s no error thrown at that point, the function simply returns `undefined`. As a result, calling something like `const t = ctx.t.get()` leads to runtime errors down the line, because the returned value is not a valid translation object or function.
However, when calling a nested path like …
=> fix: add error handling for undefined locale

src/builders/Modal.ts, src/commands/applications/entrycontext.ts, src/commands/applications/menucontext.ts, src/common/types/write.ts, src/components/componentcontext.ts, src/components/modalcontext.ts, src/structures/Interaction.ts
This pull request introduces a new `ModalCreateOptions` interface to enhance the functionality of the `modal` method across various contexts. It allows developers to specify options such as a timeout for waiting on modal submissions.
=> feat: waitFor modals

src/structures/Interaction.ts, src/types/payloads/_interactions/modalSubmit.ts
The discord api docs say one thing:
But the api returns other thing:
=> fix: modal input value
